logging:
    level:
        threewks: DEBUG
        org.springframework: INFO
        # Below is to log servlet response mapping exceptions
        org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod: TRACE

app:
    name: <%= projectName %>
    host: https://<%= project %>-dev.appspot.com

tasks:
    email:
        queue: default
        invite: /_ah/tasks/send-user-invite

spring:
    mail:
        default-encoding: UTF-8

    jackson:
        serialization.WRITE_DATES_AS_TIMESTAMPS: false
        default-property-inclusion: non_null

    thymeleaf:
        prefix: /WEB-INF/th/
        mode: LEGACYHTML5

    contrib:
        gae:
            security:
                remember-me:
                    key: 'tb:[91bt;6u6N:aUh|(mm}!$b0a |{|+6&P;3`<]tD wtAbCUe|uG =IYQx^(9d}'
