spring:
    contrib:
        gae:
            security:
                remember-me:
                    key: '<%= localKey %>'

    thymeleaf:
        cache: false

app:
    host: http://localhost:3000
