spring:
    contrib:
        gae:
            security:
                remember-me:
                    key: '<%= uatKey %>'

    mail:
        host: smtp.gmail.com
        port: 587
        username: springbuskers@gmail.com
        password: 3Wks1234
        properties:
            mail:
                smtp:
                    starttls:
                        required: true
app:
    host: https://<%= project %>-uat.appspot.com
